spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    baseline-on-migrate: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

axon:
  axonserver:
    servers: localhost:8124