spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/postgres
    username: product-service
    password: product-service
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
